// DO NOT EDIT THIS FILE.
// This file is written automatically by a “Run Script” build phase
#define ACTION_CLASSES \
        @"ClickAction", \
        @"ColorPickerAction", \
        @"DoubleclickAction", \
        @"DragDownAction", \
        @"DragUpAction", \
        @"KeyDownAction", \
        @"KeyPressAction", \
        @"KeyUpAction", \
        @"MoveAction", \
        @"PrintAction", \
        @"TripleclickAction", \
        @"TypeAction", \
        @"WaitAction", \
        nil
